services:
  # Production frontend service
  frontend:
    build:
      context: ./dewdrop
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - nginx_logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:80/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  # Development service (uncomment to use for development)
  # dev:
  #   build:
  #     context: ./dewdrop
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_SUPABASE_URL=${SUPABASE_URL}
  #     - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
  #   volumes:
  #     - ./dewdrop:/app
  #     - /app/node_modules
  #   command: npm run dev
  #   restart: unless-stopped

volumes:
  nginx_logs:
